In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from typing import Dict


# config: Dict = {
#     "train_data_path": "C:/Users/JPhillips/ldz/data/processed/train.csv",
#     "test_data_path": "C:/Users/JPhillips/ldz/data/processed/test.csv",
# }
config: Dict = {
    "epochs": 2,
    "batch_size": 2,
    "learning_rate": 3e-4,
    "train_data_path": "/mnt/c/Users/JPhillips/ldz/data/processed/train.csv",
    "test_data_path": "/mnt/c/Users/JPhillips/ldz/data/processed/test.csv",
}

2022-05-13 16:28:53.591891: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-13 16:28:53.591974: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [27]:
train_data = pd.read_csv(config["train_data_path"])
# train_data.head()

In [25]:
features = train_data.copy()
labels = features.pop("demand")

# features.head(), labels.head()

In [24]:
features = np.array(features)
labels = np.array(labels)

In [22]:
train_dataset = tf.data.Dataset.from_tensor_slices((features, labels))
train_dataset = train_dataset.batch(config["batch_size"])
train_dataset

In [18]:
from networks.base import LinearModel

In [19]:
model = LinearModel(num_outputs=1)
model.compile(
    loss = "mse",
    optimizer = tf.keras.optimizers.Adam(learning_rate=config["learning_rate"])
)

In [20]:
history = model.fit(
    train_dataset,
    epochs=config["epochs"],
)

Epoch 1/2
1644/1644 [==============================] - 3s 2ms/step - loss: 8298.8564
Epoch 2/2
1644/1644 [==============================] - 3s 2ms/step - loss: 4265.8594

In [33]:
train_data.shape

(3287, 73)

In [34]:
train_data = pd.read_csv(config["train_data_path"])

In [41]:
val_ratio = 0.1

In [55]:
import math

num_train = math.floor(len(train_data) * (1 - val_ratio))
num_train

2958

In [57]:
tr = train_data.iloc[:num_train,:]
val = train_data.iloc[num_train:,:]

In [58]:
len(tr), len(val)

(2958, 329)

In [59]:
val.head()

,demand,temp_1,temp_night_1,wind_1,wind_night_1,ssrd_ratio_1,temp_2,temp_night_2,wind_2,wind_night_2,...,wind_13,wind_night_13,ssrd_ratio_13,is_weekend,sin_yday,cos_yday,sin_2yday,cos_2yday,sin_3yday,cos_3yday
2958,214.378929,0.409854,0.343100,0.255028,0.112973,0.577334,0.388132,0.336104,0.304215,0.122571,...,0.286081,0.059814,0.262081,0,0.579421,0.815028,0.944489,0.328542,0.960150,-0.279486
2959,187.858836,0.454034,0.346822,0.166471,0.056615,0.501684,0.447833,0.345619,0.152870,0.050346,...,0.176648,0.059903,0.765656,0,0.593327,0.804962,0.955211,0.295927,0.944489,-0.328542
2960,207.003987,0.389790,0.339222,0.222046,0.063465,0.334187,0.379257,0.327338,0.181485,0.042579,...,0.133533,0.039935,0.561342,0,0.607058,0.794658,0.964806,0.262962,0.926324,-0.376728
2961,231.073119,0.347225,0.325483,0.281415,0.088531,0.372065,0.337910,0.316332,0.237201,0.061591,...,0.264423,0.077180,0.453029,0,0.620609,0.784120,0.973264,0.229688,0.905702,-0.423914
2962,237.020696,0.339057,0.322746,0.306561,0.109995,0.234136,0.344193,0.323718,0.335377,0.133774,...,0.295377,0.106222,0.445678,0,0.633978,0.773351,0.980575,0.196143,0.882679,-0.469977

In [60]:
tr.head()

,demand,temp_1,temp_night_1,wind_1,wind_night_1,ssrd_ratio_1,temp_2,temp_night_2,wind_2,wind_night_2,...,wind_13,wind_night_13,ssrd_ratio_13,is_weekend,sin_yday,cos_yday,sin_2yday,cos_2yday,sin_3yday,cos_3yday
0,248.551330,0.326607,0.313105,0.164659,0.060791,0.398739,0.305283,0.312067,0.139191,0.060370,...,0.154286,0.045850,0.440716,0,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
1,242.671902,0.332177,0.293611,0.232767,0.058776,0.790528,0.340104,0.300784,0.189118,0.042210,...,0.217911,0.063559,0.571132,0,0.017166,0.999853,0.034328,0.999411,0.051479,0.998674
2,251.157507,0.279943,0.285802,0.170879,0.076830,0.706229,0.292363,0.292311,0.196887,0.098099,...,0.107576,0.031972,0.898837,1,0.034328,0.999411,0.068615,0.997643,0.102821,0.994700
3,260.073426,0.290286,0.307029,0.271629,0.098776,0.520350,0.308587,0.318814,0.279771,0.112688,...,0.152281,0.053421,0.376753,1,0.051479,0.998674,0.102821,0.994700,0.153891,0.988088
4,277.125461,0.290138,0.284401,0.321351,0.085537,0.747497,0.307230,0.294940,0.250564,0.060241,...,0.269372,0.064238,0.603583,0,0.068615,0.997643,0.136906,0.990584,0.204552,0.978856

In [61]:
train_data.head()

,demand,temp_1,temp_night_1,wind_1,wind_night_1,ssrd_ratio_1,temp_2,temp_night_2,wind_2,wind_night_2,...,wind_13,wind_night_13,ssrd_ratio_13,is_weekend,sin_yday,cos_yday,sin_2yday,cos_2yday,sin_3yday,cos_3yday
0,248.551330,0.326607,0.313105,0.164659,0.060791,0.398739,0.305283,0.312067,0.139191,0.060370,...,0.154286,0.045850,0.440716,0,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
1,242.671902,0.332177,0.293611,0.232767,0.058776,0.790528,0.340104,0.300784,0.189118,0.042210,...,0.217911,0.063559,0.571132,0,0.017166,0.999853,0.034328,0.999411,0.051479,0.998674
2,251.157507,0.279943,0.285802,0.170879,0.076830,0.706229,0.292363,0.292311,0.196887,0.098099,...,0.107576,0.031972,0.898837,1,0.034328,0.999411,0.068615,0.997643,0.102821,0.994700
3,260.073426,0.290286,0.307029,0.271629,0.098776,0.520350,0.308587,0.318814,0.279771,0.112688,...,0.152281,0.053421,0.376753,1,0.051479,0.998674,0.102821,0.994700,0.153891,0.988088
4,277.125461,0.290138,0.284401,0.321351,0.085537,0.747497,0.307230,0.294940,0.250564,0.060241,...,0.269372,0.064238,0.603583,0,0.068615,0.997643,0.136906,0.990584,0.204552,0.978856

In [34]:
df_1 = train_data.iloc[:1000,:]
df_2 = train_data.iloc[1000:,:]

In [40]:
df_1.shape, df_2.shape, train_data.shape

((1000, 73), (2287, 73), (3287, 73))